#include "decisions_data.h"

const ConditionInstr condition_pool[CONDITION_POOL_COUNT] = {
    { CONDOP_COUNTRY_IS, 9, 0 },
    { CONDOP_COUNTRY_IS, 9, 0 },
    { CONDOP_RULING_IS, 3, 0 },
    { CONDOP_AND, 0, 0 },
    { CONDOP_COUNTRY_IS, 9, 0 },
    { CONDOP_RULING_IS, 3, 0 },
    { CONDOP_AND, 0, 0 },
    { CONDOP_COUNTRY_IS, 9, 0 },
    { CONDOP_STABILITY_GE, 75, 0 },
    { CONDOP_AND, 0, 0 },
    { CONDOP_CONTROLS_PROVINCE, 253, 0 },
    { CONDOP_AND, 0, 0 },
    { CONDOP_COUNTRY_IS, 9, 0 },
    { CONDOP_STABILITY_GE, 75, 0 },
    { CONDOP_AND, 0, 0 },
    { CONDOP_CONTROLS_PROVINCE, 253, 0 },
    { CONDOP_AND, 0, 0 },
    { CONDOP_CONTROLS_PROVINCE, 413, 0 },
    { CONDOP_COUNTRY_IS, 9, 0 },
    { CONDOP_STABILITY_GE, 75, 0 },
    { CONDOP_AND, 0, 0 },
    { CONDOP_CONTROLS_PROVINCE, 253, 0 },
    { CONDOP_AND, 0, 0 },
    { CONDOP_CONTROLS_PROVINCE, 413, 0 },
    { CONDOP_CONTROLS_PROVINCE, 328, 0 },
    { CONDOP_AND, 0, 0 },
    { CONDOP_CONTROLS_PROVINCE, 410, 0 },
    { CONDOP_AND, 0, 0 },
};

const EffectInstr effect_pool[EFFECT_POOL_COUNT] = {
    { EFFECTOP_SET_RULING_IDEOLOGY, 3, 0 },
    { EFFECTOP_ADD_STABILITY, -50, 0 },
    { EFFECTOP_SET_PROVINCE_OWNER, 69, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 253, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 452, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 451, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 68, -1 },
    { EFFECTOP_ADD_STABILITY, 20, 0 },
    { EFFECTOP_SET_PROVINCE_OWNER, 323, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 450, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 413, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 336, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 337, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 330, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 328, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 312, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 329, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 332, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 410, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 412, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 417, -1 },
    { EFFECTOP_SET_PROVINCE_OWNER, 407, 6 },
    { EFFECTOP_SET_PROVINCE_OWNER, 371, 6 },
    { EFFECTOP_SET_PROVINCE_OWNER, 398, 6 },
    { EFFECTOP_SET_PROVINCE_OWNER, 339, 6 },
    { EFFECTOP_ADD_SUPPORT, 3, 100 },
};

const Decision decisions[DECISION_COUNT] = {
    { "Return of the Habsburgs", "Gott erhalte Otto den Kaiser", "Otto von Habsburg becomes head of state.", "", -1, 0, 1, 0, 65535, 0, 2 },
    { "Return of Hungary", "We have been separated from our hungarian brothers for too long. But that is about to change.", "Austria Annexes the Kingdom of Hungary.", "", -1, 1, 3, 0, 65535, 2, 5 },
    { "Stabilize the country", "We are unstable. fuck", "", "", 2, 0, 65535, 0, 65535, 7, 1 },
    { "Annex Czechoslovakia", "Edvard Benes tonto panoli", "", "", -1, 4, 3, 7, 5, 8, 10 },
    { "Partition Poland", "Get rekt lmaooooooo", "", "", -1, 12, 5, 17, 1, 18, 7 },
    { "Restore the Empire", "", "", "", -1, 18, 5, 23, 5, 25, 1 },
};
